name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Adjust if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'  # Adjust to your .NET version

      - name: Install dependencies
        run: dotnet restore

      - name: Build Blazor app
        run: dotnet publish -c Release -o output

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase CLI
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT_KEY}" > ${HOME}/firebase-service-account.json
          firebase login:ci --token ${HOME}/firebase-service-account.json

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
